FROM node:18-alpine3.17

ENV NODE_ENV development

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

RUN pnpm prisma generate

COPY . .

EXPOSE 5173
EXPOSE 24678
CMD ["pnpm", "dev", "--host", "0.0.0.0"]